on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'orthanq'
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: rust
          package-name: orthanq

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Install Pixi
        if: ${{ steps.release.outputs.release_created }}
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: latest

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pixi install

      - name: Publish crate
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pixi run cargo publish --token "${{ secrets.CRATES_IO_TOKEN }}"
